appName = "fsfc"

[set]
# 时间单位：秒

# 手动同步间隔时间
scanGap = 10
# 自动同步列表更新间隔时间
# scanMlGapUpdate = 60
scanMlGapUpdate = 12
# 自动同步间隔时间（默认一天）
# scanMlGapSync = 86400
scanMlGapSync = 60
# 自动同步文件数量，不超过150
MlTopK = 5

# windows下手动指定同步文件夹
localPath = "C:\\Users\\14595\\Desktop\\FSFC\\fsfc_windows"
# linux服务器同步文件夹地址
remotePath = "/go/project/syncDir"
# Recent文件夹地址
RecentPath = "C:\\Users\\14595\\AppData\\Roaming\\Microsoft\\Windows\\Recent"

[web]
localIp = "127.0.0.1"
localPort = "8888"
remoteIp = "124.70.57.7"
remotePort = "5555"
remoteMlIp = "127.0.0.1"
remoteMlPort = "5000"

[log]
level = "debug"
path = "logs/chat.log"

[staticPath]
filePath = "web/static/file/"



# [msgChannelType]
# channelType = "gochannel"
#
# kafkaHosts = "kafka:9092"
# kafkaTopic = "go-chat-message"