appName = "fsfc"

[set]
# 单位：秒
scanGap = 6
# 默认 fsfc/
rootPath = '../'

[log]
level = "debug"
path = "logs/chat.log"

[staticPath]
filePath = "web/static/file/"



# [msgChannelType]
# channelType = "gochannel"
#
# kafkaHosts = "kafka:9092"
# kafkaTopic = "go-chat-message"